"""empty message

Revision ID: e65d412c48dd
Revises: 
Create Date: 2025-02-27 21:43:18.172898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65d412c48dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor_config', schema=None) as batch_op:
        batch_op.drop_column('discord_webhook_url')

    with op.batch_alter_table('proxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_proxy_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'proxy_list', ['list_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_proxy_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('list_id')

    with op.batch_alter_table('monitor_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_webhook_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
